os:
  primary_interface: net0
  primary_mac: C8:F7:50:FC:F4:A5
  vlans:
    - 200
  hostname: k3s-delta
  additional_mounts:
    - path: /var/lib/longhorn
      opts: defaults,noatime
      src: /dev/nvme0n1p3
      fstype: ext4
watchdog:
  module: iTCO_wdt
k3s:
  labels:
    video_processing: "true"
    ups_controller: "true"
