
os:
  primary_interface: net0
  primary_mac: 00:23:24:ac:fb:8a
  vlans:
    - 100
    - 200
  hostname: k3s-charlie
  lvm:
    vgs:
      vg_data:
        disks:
          - /dev/sda3
        lvs:
          - name: lv_data
            size: 60%FREE
            fstype: ext4
  additional_mounts:
    - path: /var/lib/longhorn
      opts: defaults,noatime
      src: /dev/vg_data/lv_data
      fstype: ext4
  udev_rules:
    - name: mobile
      rule: 'SUBSYSTEM=="tty", ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1506", ENV{ID_USB_INTERFACE_NUM}=="00", SYMLINK+="mobile"'
watchdog:
  module: iTCO_wdt
k3s:
  labels:
    modem_controller: "true"
    video_processing: "true"
