os:
  primary_interface: net0
  primary_mac: d8:cb:8a:d1:50:25
  hostname: k3s-bravo
  additional_mounts:
    - path: /var/lib/longhorn
      opts: defaults,noatime
      src: /dev/sda3
      fstype: ext4
watchdog:
  module: iTCO_wdt
k3s:
  labels:
    video_processing: "true"
    zigbee_controller: "true"
