os:
  primary_interface: eno1
  hostname: k3s-bravo
  additional_mounts:
    - path: /var/lib/longhorn
      opts: defaults,noatime
      src: /dev/sda3
      fstype: ext4
watchdog:
  module: iTCO_wdt
k3s:
  labels:
    video_processing: "true"
    zigbee_controller: "true"
