os:
  primary_interface: net0
  primary_mac: d8:cb:8a:d1:50:25
  vlans:
    - 100
    - 200
  hostname: k3s-bravo
  lvm:
    vgs:
      vg_data:
        disks:
          - /dev/sda3
        lvs:
          - name: lv_data
            size: 60%FREE
            fstype: ext4
  additional_mounts:
    - path: /var/lib/longhorn
      opts: defaults,noatime
      src: /dev/vg_data/lv_data
      fstype: ext4
  udev_rules:
    - name: zigbee
      rule: 'SUBSYSTEM=="tty", ATTRS{idVendor}=="1cf1", ATTRS{idProduct}=="0030", ATTRS{serial}=="DE2151967", SYMLINK+="zigbee"'
watchdog:
  module: iTCO_wdt
k3s:
  labels:
    video_processing: "true"
    zigbee_controller: "true"
