---
- name: Generate SSH keys for nodes
  hosts:
    - k8s_master_primary
  gather_facts: true
  tasks:
    - name: Generate SSH key
      openssh_keypair:
        path: /root/.ssh/id_rsa
      become: true
    - name: Cat SSH pub key
      command: cat /root/.ssh/id_rsa.pub
      register: cat_ssh_pub
      become: true
    - name: Set SSH pubkey fact
      set_fact:
        ansible_global_ssh_key: "{{ {'user': 'root', 'key': cat_ssh_pub.stdout} }}"
      delegate_facts: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['all'] }}"

- name: Configure k8s master
  hosts:
    - k8s_master_primary
    - k8s_master
  gather_facts: true
  tasks:
    - name: Base config
      vars:
        timezone: "{{ global.timezone }}"
        hostname: "{{ os.hostname }}"
        swap_file: "{{ os.swap_file }}"
        ssh_keys: "{{ os.ssh_keys + [ ansible_global_ssh_key ] }}"
      include_tasks: tasks/base_config.yaml

    - name: Configure networking
      vars:
        primary_interface: "{{ os.primary_interface }}"
        dns_servers: "{{ global.dns.servers }}"
      include_tasks: tasks/configure_networking.yaml

    - name: Mount additional disks
      vars:
        additional_mounts: "{{ os.additional_mounts | default([]) }}"
      include_tasks: tasks/additional_mounts.yaml

    - name: Enforce performance cpu governor
      copy:
        dest: /etc/default/cpufrequtils
        content: |
          GOVERNOR="performance"
      become: true

    - name: Set GRUB_CMDLINE_LINUX_DEFAULT
      lineinfile:
        state: present
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: GRUB_CMDLINE_LINUX_DEFAULT="cpufreq.default_governor=performance intel_pstate=disable"
      become: true
      register: grub_config

    - name: Update grub config
      command: update-grub
      when: grub_config.changed
      become: true

    - name: Manage packages
      vars:
        install: "{{ package.install | default([]) }}"
        remove: "{{ package.remove | default([]) }}"
      include_tasks: tasks/manage_packages.yaml

    - name: Manage services
      vars:
        disable: "{{ service.disable | default([]) }}"
        enable: "{{ service.enable | default([]) }}"
        create: "{{ service.create | default({}) }}"
      include_tasks: tasks/manage_services.yaml

- name: Upgrade k8s master
  hosts:
    - k8s_master_primary
    - k8s_master
  gather_facts: true
  serial: 1
  tasks:
    - block:
      - name: Upgrade
        vars:
          upgrade: true
        include_tasks: tasks/manage_packages.yaml

      - name: Reboot
        reboot:
          post_reboot_delay: 120
          reboot_timeout: 300
        become: true

      when:
      - operation is defined
      - operation == 'upgrade'
      any_errors_fatal: true
