validators:
  "deployment/generic":
    "privileged_false":
      skip:
        [
          "smart-home/zigbee2mqtt",
          "smart-home/sms-gammu",
          "smart-home/recorder",
          "home-infra/network-ups-tools",
          "home-infra/debugpod",
        ]
    "runasuser_not_root":
      skip: ["home-infra/debugpod"]
    "capabilities_add_missing":
      skip: ["kube-system/coredns", "monitoring/prometheus-blackbox-exporter"]
    "resources_cpu_present":
      skip: ["home-infra/debugpod", "smart-home/esphome"]
    "resources_memory_present":
      skip:
        [
          "home-infra/debugpod",
          "smart-home/esphome",
          "kube-system/metrics-server",
          "longhorn-system/csi-attacher",
          "longhorn-system/csi-provisioner",
          "longhorn-system/csi-resizer",
          "longhorn-system/csi-snapshotter",
          "longhorn-system/longhorn-driver-deployer",
          "longhorn-system/longhorn-ui",
          "monitoring/prometheus-server",
        ]
    "liveness_probe_present":
      skip:
        [
          "home-infra/debugpod",
          "cert-manager/cert-manager-cainjector",
          "longhorn-system/csi-attacher",
          "longhorn-system/csi-provisioner",
          "longhorn-system/csi-resizer",
          "longhorn-system/csi-snapshotter",
          "longhorn-system/longhorn-driver-deployer",
          "longhorn-system/longhorn-ui",
        ]
  "deployment/with_pvc_or_hostpath":
    "strategy_recreate":
      skip:
        [
          "longhorn-system/csi-attacher",
          "longhorn-system/csi-provisioner",
          "longhorn-system/csi-resizer",
          "longhorn-system/csi-snapshotter",
        ]
  "deployment/without_pvc_or_hostpath":
    "strategy_rollingupdate":
      skip: ["monitoring/prometheus-server"]
  "deployment/with_multiple_replicas":
  "daemonset/generic":
    "privileged_false":
      skip:
        [
          "kube-system/kube-multus-ds",
          "longhorn-system/engine-image-ei-f4f7aa25",
          "longhorn-system/longhorn-csi-plugin",
          "longhorn-system/longhorn-manager",
        ]
    "capabilities_add_missing":
      skip:
        [
          "home-infra/chrony",
          "longhorn-system/longhorn-csi-plugin",
          "metallb-system/metallb-speaker",
        ]
    "resources_memory_present":
      skip:
        [
          "longhorn-system/engine-image-ei-f4f7aa25",
          "longhorn-system/longhorn-csi-plugin",
          "longhorn-system/longhorn-manager",
          "metallb-system/metallb-speaker",
        ]
    "liveness_probe_present":
      skip:
        [
          "kube-system/kube-multus-ds",
          "longhorn-system/longhorn-csi-plugin",
          "longhorn-system/longhorn-manager",
          "metallb-system/metallb-speaker",
        ]
  "daemonset/with_pvc_or_hostpath":
    "strategy_recreate":
      skip:
        [
          "home-infra/chrony",
          "longhorn-system/engine-image-ei-f4f7aa25",
          "longhorn-system/longhorn-csi-plugin",
          "monitoring/prometheus-prometheus-node-exporter",
        ]
  "daemonset/without_pvc_or_hostpath":
  "ingress_route/generic":
    "required_middlewares":
      skip:
        [
          "home-infra/authelia",
          "smart-home/home-assistant",
          "self-hosted/files",
          "self-hosted/vaultwarden",
        ]
    "tls_present":
      skip: ["smart-home/home-assistant-http", "home-infra/unifi-http"]
  "service/generic":
  "service/loadbalancer":
  "cron_job/generic":
  "cron_job/backup":
  "cron_job/restore":

