- name: Mount additional disks
  mount:
    path: "{{ item.path }}"
    opts: "{{ item.opts | default('defaults') }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    passno: 2
    state: mounted
  with_items: "{{ additional_mounts }}"
  when: additional_mounts is defined
  become: true
