- name: configure default/watchdog
  vars:
    create:
      custom-default-watchdog:
        dst: /etc/default/watchdog
        src: "../templates/default_watchdog.j2"
        permission: "0644"
        notify: watchdog
  include_tasks: custom_files.yaml

- name: configure watchdog.conf
  vars:
    create:
      custom-default-watchdog:
        dst: /etc/watchdog.conf
        src: "../templates/watchdog.conf.j2"
        permission: "0644"
        notify: watchdog
  include_tasks: custom_files.yaml
