- name: configure netplan
  vars:
    create:
      custom-systemd-resolver:
        dst: /etc/netplan/00-installer-config.yaml
        src: "../templates/netplan.yaml.j2"
        permission: "0644"
        execute: 'netplan apply'
  include_tasks: custom_files.yaml

- name: Create proper resolv.conf symlink
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: true

- name: configure systemd-resolver
  vars:
    create:
      custom-systemd-resolver:
        dst: /etc/systemd/resolved.conf
        src: "../templates/resolved.conf.j2"
        permission: "0644"
        notify: systemd-resolved
  include_tasks: custom_files.yaml

