- name: netplan configure
  template:
    src: templates/netplan.yaml.j2
    dest: /etc/netplan/00-installer-config.yaml
  register: netplan_config
  become: true

- name: netplan apply
  command: netplan apply
  when: netplan_config.changed
  become: true

- name: Create proper resolv.conf symlink
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: true

- name: systemd-resolver configure
  template:
    src: templates/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  register: systemd_resolver_config
  become: true

- name: systemd-resolver restart
  systemd:
    name: systemd-resolved
    state: restarted
  when: systemd_resolver_config.changed
  become: true
