- name: create destination directory for custom files
  file:
    path: "{{ custom_file.value.dst | dirname }}"
    state: directory
    mode: 0755
  with_dict: "{{ create }}"
  loop_control:
    loop_var: custom_file
  when: create is defined
  become: true

- name: create custom files
  vars:
    data: "{{ custom_file.value.data | default(omit) }}"
  template:
    src: "{{ custom_file.value.src }}"
    dest: "{{ custom_file.value.dst }}"
    mode: "{{ custom_file.value.permission }}"
  with_dict: "{{ create }}"
  loop_control:
    loop_var: custom_file
  when: create is defined
  become: true
  register: custom_file_created

- name: restart service
  service:
    name: "{{ custom_file.custom_file.value.notify }}"
    state: restarted
  with_list: "{{ custom_file_created.results }}"
  loop_control:
    loop_var: custom_file
  when:
    - custom_file.changed
    - custom_file.custom_file.value.notify is defined
  become: true

- name: run command
  command: "{{ custom_file.custom_file.value.execute }}"
  with_list: "{{ custom_file_created.results }}"
  loop_control:
    loop_var: custom_file
  when:
    - custom_file.changed
    - custom_file.custom_file.value.execute is defined
  become: true
