- name: Create destination directory for custom files
  file:
    path: "{{ item.value.dst | dirname }}"
    state: directory
    mode: 0755
  with_dict: "{{ create }}"
  when: create is defined
  become: true

- name: Create custom files
  template:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dst }}"
    mode: "{{ item.value.permission }}"
  with_dict: "{{ create }}"
  when: create is defined
  become: true
  register: custom_file_created

- name: Restart service
  service:
    name: "{{ item.item.value.notify }}"
    state: restarted
  with_list: "{{ custom_file_created.results }}"
  when:
    - item.changed
    - item.item.value.notify is defined
  become: true

- name: Run command
  command: "{{ item.item.value.execute }}"
  with_list: "{{ custom_file_created.results }}"
  when:
    - item.changed
    - item.item.value.execute is defined
  become: true
