- name: Check get.k3s.io accessibility
  uri:
    url: https://get.k3s.io
  retries: 3
  delay: 5
  register: get_k3s_ready
  until: get_k3s_ready.status == 200

- name: Create custom coredns file
  vars:
    create:
      custom-coredns:
        dst: /var/lib/rancher/k3s/server/manifests/z-custom-coredns.yaml
        src: "../templates/k3s-custom-coredns.yaml.j2"
        permission: "0600"
  include_tasks: tasks/custom_files.yaml

- name: Env used for k3s deployment
  debug:
    msg: "{{ env }}"

- name: Install K3s
  shell: "curl -vsfL https://get.k3s.io | sh -s -"
  environment: "{{ env }}"
  become: true

- name: Wait for K3s
  shell: "kubectl get node | grep '^{{ os.hostname }}[[:space:]]*Ready'"
  retries: 60
  delay: 2
  register: k3s_ready
  until: k3s_ready.rc == 0
  become: true
