- name: Check get.k3s.io accessibility
  uri:
    url: https://get.k3s.io
  retries: 3
  delay: 5
  register: get_k3s_ready
  until: get_k3s_ready.status == 200

- name: Env used for k3s deployment
  debug:
    msg: "{{ env }}"

- name: Install K3s
  shell: "curl -vsfL https://get.k3s.io | sh -s -"
  environment: "{{ env }}"
  become: true

- name: Wait for K3s node registration
  shell: "kubectl get node | grep '^{{ os.hostname }}[[:space:]]'"
  retries: 60
  delay: 2
  register: k3s_ready
  until: k3s_ready.rc == 0
  become: true

- block:
  - name: Get k3s secrets-encrypt status
    command: k3s secrets-encrypt status
    register: k3s_enc_status
    changed_when: false

  - name: Fail if secrets encryption is not enabled
    fail:
      msg: "k3s secrets encryption is NOT enabled: {{ k3s_enc_status.stdout | replace('\n', ' ') }}"
    when: "'Encryption Status: Enabled' not in k3s_enc_status.stdout"

  - name: Report secrets encryption status
    debug:
      msg: "{{ k3s_enc_status.stdout_lines }}"
  become: true

- name: Create CNI dirs
  file:
    path: /opt/cni/bin
    state: directory
  become: true

- name: Unpack CNI
  unarchive:
    src: "{{ k3s.cni_url }}"
    dest: /opt/cni/bin/
    remote_src: yes
  become: true

- name: Manage services
  vars:
    create: "{{ k3s.service.create }}"
  include_tasks: tasks/manage_services.yaml

- name: Deploy multus CNI
  vars:
    create:
      custom-multus-cni-manifest:
        dst: /var/lib/rancher/k3s/server/manifests/multus-daemonset.yaml
        src: "../templates/multus-daemonset.yaml"
        permission: "0644"
  include_tasks: tasks/custom_files.yaml

- name: Restart custom services
  systemd:
    name: "{{ item.key }}"
    state: restarted
  with_dict: "{{ k3s.service.create }}"
  become: true
