- set_fact:
    dst: "../../{{ item | replace('../templates/', '') | replace('.j2', '') }}"

- name: Create destination directory
  file:
    path: "{{ dst | dirname }}"
    state: directory
    mode: 0755

- name: Render template
  template:
    src: "{{ item }}"
    dest: "{{ dst }}"
  register: renderer_template

- name: Append changed manifests
  set_fact:
    changed_manifests: "{{ changed_manifests + [  item | replace('../templates/', '') | replace('.j2', '') ] }}"
  when: renderer_template.changed
