---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubernetes-reflector
  namespace: kube-system
spec:
  repo: https://emberstack.github.io/helm-charts
  chart: reflector
  targetNamespace: kube-system
